name: Java CI

on:
  push:
    branches: [ '*', '*/*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        javaver: [17]
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.javaver }}
        distribution: 'temurin'

    - name: Build
      run: mvn package
